## Sudoku

![Sudoku](http://upload.wikimedia.org/wikipedia/commons/f/ff/Sudoku-by-L2G-20050714.svg)

**Sudoku** is a number puzzle played on a 9x9 grid. The challenge is to place a digit between 1 and 9 inclusive in each empty cell, such that the completed grid obeys the following rules:

* Each row contains the numbers 1 to 9 once and only once.
* Each column contains the numbers 1 to 9 once and only once.
* Each 3x3 subgrid contains the numbers 1 to 9 once and only once.

The most natural formulation of this problem would probably be something like

$$x_{i,j} \in \{1, 2, \dots, 9\}$$

which is of course something we can do with integer programming:

$$1 \leq x_{i,j} \leq 9, ~ integer$$

The challenge now is the constraints. One observation is that the numbers 1 to 9 add up to 45, so we could try something like:

$$ \sum_{j=1}^9 x_{i,j} = 45 $$

And something similar for the columns and squares.

In [3]:
init_vals = [
5 3 0 0 7 0 0 0 0
6 0 0 1 9 5 0 0 0
0 9 8 0 0 0 0 6 0
8 0 0 0 6 0 0 0 3
4 0 0 8 0 3 0 0 1
7 0 0 0 2 0 0 0 6
0 6 0 0 0 0 2 8 0
0 0 0 4 1 9 0 0 5
0 0 0 0 8 0 0 7 9
]

using JuMP, Gurobi
function sudoku1()
    sudoku = Model(solver=GurobiSolver(OutputFlag=0))
    @variable(sudoku, 1 <= x[1:9,1:9] <= 9, Int)
    @constraint(sudoku, rows[i=1:9], sum(x[i,:]) == 45)
    @constraint(sudoku, cols[j=1:9], sum(x[:,j]) == 45)
    @constraint(sudoku,subgrid[i=1:3:7,j=1:3:7], sum(x[i:i+2,j:j+2]) == 45)
    for i in 1:9, j in 1:9
        if init_vals[i,j] != 0
            @constraint(sudoku, x[i,j] == init_vals[i,j])
        end
    end
    
    solve(sudoku)
    
    Int.(getvalue(x))
end
grid1 = sudoku1()

9×9 Array{Int64,2}:
 5  3  9  9  7  1  1  1  9
 6  1  1  1  9  5  9  4  9
 3  9  8  1  9  3  5  6  1
 8  9  1  9  6  1  1  7  3
 4  9  1  8  1  3  9  9  1
 7  1  5  6  2  9  8  1  6
 9  6  5  6  2  5  2  8  2
 1  6  8  4  1  9  9  2  5
 2  1  7  1  8  9  1  7  9

Academic license - for non-commercial use only


Well that didn't work. Our model can't have been correct. This shows the importance of validating the output from an optimization model to make sure it makes sense and actually reflects the problem you are trying to solve.

## Exercise

Let's write a function to validate any sudoku solution and check if it is valid:

In [4]:
function check_sudoku(grid)
    isvalid = true
    for row = 1:9
        if length(unique(grid[row, :])) != 9
            println("row $row is invalid")
            isvalid = false
        end
    end
    for col = 1:9
        if length(unique(grid[:, col])) != 9
            println("col $col is invalid")
            isvalid = false
        end
    end
    for i = 1:3:7, j = 1:3:7
        if length(unique(grid[i:i+2, j:j+2])) != 9
            println("3x3 square ($i,$j) is invalid")
            isvalid = false
        end
    end
    return isvalid
end    

check_sudoku (generic function with 1 method)

Let's try it out:

In [5]:
check_sudoku(grid1)

false

row 1 is invalid
row 2 is invalid
row 3 is invalid
row 4 is invalid
row 5 is invalid
row 6 is invalid
row 7 is invalid
row 8 is invalid
row 9 is invalid
col 2 is invalid
col 3 is invalid
col 4 is invalid
col 5 is invalid
col 6 is invalid
col 7 is invalid
col 8 is invalid
col 9 is invalid
3x3 square (1,1) is invalid
3x3 square (1,4) is invalid
3x3 square (1,7) is invalid
3x3 square (4,1) is invalid
3x3 square (4,4) is invalid
3x3 square (4,7) is invalid
3x3 square (7,1) is invalid
3x3 square (7,4) is invalid
3x3 square (7,7) is invalid


## New formulation

Let's fix our formulation so it is correct. We can change our **variables**: $x_{i,j,k} = 1$ iff the number $k$ will appear in cell $(i,j)$. We can now use our 0-1 integer programming knowledge to model the problem. Consider the "row" constraints: we want each number to appear once and only once. This is equivalent to saying that

$$\sum_{j=1}^9 x_{i,j,k} = 1 \quad \forall i, k$$

We can now model this as a $9\times 9\times 9$ dimensional problem - thats a lot of binary variables, surely Gurobi won't like that!

In [6]:
function sudoku2()
    sudoku = Model(solver=GurobiSolver())

    @variable(sudoku, x[i=1:9, j=1:9, k=1:9], Bin)

    @constraints(sudoku, begin
        # Constraint 1 - Exactly one value appears in each cell
        cell[i=1:9, j=1:9], sum(x[i,j,:]) == 1
        # Constraint 2 - Each value appears in each row exactly once
        row[i=1:9, k=1:9], sum(x[i,:,k]) == 1
        # Constraint 3 - Each value appears in each column exactly once
        col[j=1:9, k=1:9], sum(x[:,j,k]) == 1
        # Constraint 4 - Each value appears in each 3x3 subgrid exactly once
        subgrid[i=1:3:7,j=1:3:7,val=1:9], sum(x[i:i+2,j:j+2,val]) == 1
    end)

    # Initial solution
    for row in 1:9, col in 1:9
        if init_vals[row,col] != 0
            @constraint(sudoku, x[row, col, init_vals[row, col]] == 1)
        end
    end
    
    solve(sudoku)
    
    getvalue(x)
end
grid2 = sudoku2()

9×9×9 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0

[:, :, 3] =
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.

Academic license - for non-commercial use only
Optimize a model with 354 rows, 729 columns and 2946 nonzeros
Variable types: 0 continuous, 729 integer (729 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [0e+00, 0e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 354 rows and 729 columns
Presolve time: 0.00s
Presolve: All rows and columns removed

Explored 0 nodes (0 simplex iterations) in 0.00 seconds
Thread count was 1 (of 8 available processors)

Solution count 1: 0 

Optimal solution found (tolerance 1.00e-04)
Best objective 0.000000000000e+00, best bound 0.000000000000e+00, gap 0.0000%


We can check if this is a valid solution, but we have to change it into the grid format first!

In [7]:
grid2a = zeros(Int, 9, 9)
for i = 1:9
    for j = 1:9
        grid2a[i, j] = findfirst(grid2[i, j, :])
    end
end
grid2a

9×9 Array{Int64,2}:
 5  3  4  6  7  8  9  1  2
 6  7  2  1  9  5  3  4  8
 1  9  8  3  4  2  5  6  7
 8  5  9  7  6  1  4  2  3
 4  2  6  8  5  3  7  9  1
 7  1  3  9  2  4  8  5  6
 9  6  1  5  3  7  2  8  4
 2  8  7  4  1  9  6  3  5
 3  4  5  2  8  6  1  7  9

In [8]:
check_sudoku(grid2a)

true

It works!